spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    username: ${DATABASE_USERNAME:activity}
    password: ${DATABASE_PASSWORD:activity}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/activity}

discord:
  token: ${DISCORD_TOKEN:Obtain a valid bot token at https://discord.com/developers/applications}
  development-guild-id: 932728712355512331
