discord:
  token: ${DISCORD_TOKEN:Obtain a valid bot token at https://discord.com/developers/applications}
  development-guild-id: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: ${DATABASE_USERNAME:activity}
    password: ${DATABASE_PASSWORD:activity}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/activity}
